author = Riccardo "Jack" Lucchetti and Artur Tarassow
email = r.lucchetti@univpm.it
version = 0.6
date = 2024-03-02
description = Factorized kernel density estimation
tags = C14
min-version = 2021a
gui-main = fdensity_GUI
label = Factorized density
menu-attachment = MAINWIN/View/GraphVars
public = fdensity fdensity_GUI 
no-print = fdensity_GUI 
help = fdensity_help.md
sample-script = fdensity_sample.inp
