author = Riccardo "Jack" Lucchetti
email = r.lucchetti@univpm.it
version = 0.5
date = 2023-04-22
description = factorized kernel density
tags = C14
min-version = 2021a
gui-main = fdensity_GUI
label = Factorized density
menu-attachment = MAINWIN/View/GraphVars
public = fdensity fdensity_GUI 
no-print = fdensity_GUI 
help = fdensity_help.md
sample-script = fdensity_sample.inp
